---
- name: "Set Up pygreeter"
  hosts: "py"
  vars_files:
    - "./vars.yaml"
  tasks:
    - name: "Ping Instance"
      ansible.builtin.ping: {}
    - name: "Install Dependencies"
      become: true
      ansible.builtin.apt:
        pkg:
          - "acl"
          - "python3"
          - "python3-pip"
        update_cache: true
    - name: "Create a User"
      become: true
      ansible.builtin.user:
        name: "pygreeter"
    - name: "Clone the pygreeter Repository"
      become: true
      become_user: "pygreeter"
      ansible.builtin.git:
        repo: "https://github.com/zhews/pygreeter.git"
        dest: "/home/pygreeter/app"
        version: "main"
    - name: "Install Python Requirements"
      become: true
      become_user: "pygreeter"
      ansible.builtin.pip:
        requirements: "/home/pygreeter/app/requirements.txt"
    - name: "Create the pygreeter Service"
      become: true
      ansible.builtin.copy:
        src: "./pygreeter.service"
        dest: "/usr/lib/systemd/system/pygreeter.service"
        owner: "root"
        group: "root"
    - name: "Start the pygreeter Service"
      become: true
      ansible.builtin.systemd_service:
        name: "pygreeter.service"
        state: "started"
        daemon_reload: true
- name: "Set Up gogreeter"
  hosts: "go"
  vars_files:
    - "./vars.yaml"
  tasks:
    - name: "Ping Instance"
      ansible.builtin.ping: {}
    - name: "Install Dependencies"
      become: true
      ansible.builtin.apt:
        pkg:
          - "acl"
          - "golang-go"
        update_cache: true
    - name: "Create a User"
      become: true
      ansible.builtin.user:
        name: "gogreeter"
    - name: "Clone the gogreeter Repository"
      become: true
      become_user: "gogreeter"
      ansible.builtin.git:
        repo: "https://github.com/zhews/gogreeter.git"
        dest: "/home/gogreeter/app"
        version: "main"
    - name: "Build the gogreeter Application"
      become: true
      become_user: "gogreeter"
      ansible.builtin.command:
        cmd: "go build -o ./bin/gogreeter ./cmd/gogreeter"
        chdir: "/home/gogreeter/app"
        creates: "/home/gogreeter/app/bin/gogreeter"
    - name: "Create the gogreeter Service"
      become: true
      ansible.builtin.copy:
        src: "./gogreeter.service"
        dest: "/usr/lib/systemd/system/gogreeter.service"
        owner: "root"
        group: "root"
    - name: "Start the gogreeter Service"
      become: true
      ansible.builtin.systemd_service:
        name: "gogreeter.service"
        state: "started"
        daemon_reload: true
